2025-02-19T18:09:49|CRITICAL|root|Unhandled exception:Traceback (most recent call last):
  File "c:\data\python programs\camera humanitas\hyperspectralmicroscope\hyperspectral_measure.py", line 175, in run
    self.image_gen.camera.acq_start()
AttributeError: 'LoggedQuantity' object has no attribute 'acq_start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 27, in run
    self.measurement._thread_run()
  File "C:\ProgramData\anaconda3\envs\scopefoundry\lib\site-packages\ScopeFoundry\measurement.py", line 230, in _thread_run
    self.run()
  File "c:\data\python programs\camera humanitas\hyperspectralmicroscope\hyperspectral_measure.py", line 197, in run
    self.image_gen.camera.stopAcquisition()
AttributeError: 'LoggedQuantity' object has no attribute 'stopAcquisition'

